### ISSUE TITLE
Aplicar estilos con Bootstrap a Consejos

### ISSUE THREAD

**Issue by cintiabelenestrada** [cintiabelenestrada/repo-tp2#103]
Reemplazar texto generizo por el texto que haga referencia a los titulos, subtitulos, colores y formatos, etc.
Considerar el uso de las clases bootstrap para organizar todo el contenido de los archivos html:
Containers, Filas, Columnas, Alineación
El sitio se debe adaptar (ser responsive) para los diferentes tamaños de dispositivos
centrar todas las imagenes, letras

**Comment by gonzanv** [comment]
Se agrego estilos de bootstrap a consejos_de_salud.html, usando la clase "card". Tambien se agregó el atributo String "imagen"  a la clase HealthTip, este atributo corresponde a la url de una imagen que se relaciona con el consejo. Se agrego el input y label correspondiente al formulario para poder colocar una imagen al consejo.

[Branch](https://github.com/cintiabelenestrada/repo-tp2/tree/branch_VelazquezGonzaloNicolas-BootsrapConsejos)
