### ISSUE TITLE
Aplicar estilos con Bootstrap a Servicios

### ISSUE THREAD

**Issue by cintiabelenestrada** [cintiabelenestrada/repo-tp2#106]
Reemplazar texto generizo por el texto que haga referencia a los titulos, subtitulos, colores y formatos, etc.
Considerar el uso de las clases bootstrap para organizar todo el contenido de los archivos html:
Containers, Filas, Columnas, Alineación
El sitio se debe adaptar (ser responsive) para los diferentes tamaños de dispositivos

**Comment by gonzanv** [comment]
Se centró el texto y botones de las tablas de servicio de paseos mediante bootstrap.
